import { Brand } from "@/components/brand";

export default function TermsPage() {
  return <main className="legal-shell container">
    <header className="billing-top"><Brand /><a className="btn btn-soft" href="/">Voltar</a></header>
    <article className="legal-card">
      <div className="eyebrow">VERSÃO 25/08/2026</div><h1>Termos de uso</h1>
      <p className="muted">Este texto foi preparado como base operacional para lançamento do Fluxtok. Ele reduz ambiguidades no uso do serviço, mas não substitui revisão jurídica adequada ao responsável pela operação.</p>
      <h2>1. Objeto do serviço</h2><p>O Fluxtok é um software de organização operacional para sellers e equipes que trabalham com creators, amostras, campanhas, conteúdos e integrações de social commerce. O Fluxtok não substitui TikTok Shop, Mercado Pago ou outros serviços de terceiros.</p>
      <h2>2. Conta e segurança</h2><p>O usuário deve fornecer informações corretas, proteger sua senha e limitar os acessos da equipe a pessoas autorizadas. Atividades realizadas por contas válidas podem ser registradas para segurança, auditoria e suporte.</p>
      <h2>3. Teste gratuito</h2><p>Novas empresas recebem, por padrão, 7 dias de teste gratuito e sem exigência de cartão. Ao final do teste, o acesso operacional pode ser restringido até a contratação de um plano. O término do teste não gera cobrança automática sem contratação de assinatura.</p>
      <h2>4. Planos e pagamentos</h2><p>Os planos pagos atualmente disponibilizados são Essencial, por R$ 49,90, e Pro, por R$ 79,90, salvo alteração de preço apresentada antes da contratação. No cartão, a cobrança é recorrente e mensal. No Pix comum, o pagamento é avulso e libera 30 dias de acesso após confirmação, sem renovação automática. Os pagamentos são processados pelo Mercado Pago. O e-mail informado para realizar o pagamento pode ser diferente do e-mail usado no cadastro e login do Fluxtok. O e-mail de pagamento não altera as credenciais de acesso à plataforma, e o usuário declara possuir autorização para utilizá-lo no pagamento. O Fluxtok não armazena o número completo do cartão nem mantém o CPF/CNPJ informado apenas para gerar o Pix.</p>
      <h2>5. Cancelamento e renovação</h2><p>Assinaturas recorrentes no cartão podem ser canceladas pelos recursos disponibilizados no sistema, dependendo da confirmação do processador. O Pix comum não possui renovação automática: ao fim do período contratado, é necessário realizar novo pagamento para continuar. Eventuais direitos de arrependimento, estorno ou reembolso seguem a legislação aplicável e as regras do processador de pagamentos.</p>
      <h2>6. Dados inseridos pelo cliente</h2><p>O cliente é responsável pela legitimidade dos dados de creators, contatos, links e demais informações que inserir. O cliente declara que possui base adequada para tratar esses dados e que não utilizará o Fluxtok para spam, fraude, assédio ou tratamento ilícito de informações.</p>
      <h2>7. Integrações de terceiros</h2><p>Recursos dependentes de TikTok Shop, Mercado Pago, hospedagem, e-mail ou outros provedores podem sofrer indisponibilidade, alteração de API, limitação de escopo ou revisão de acesso. O Fluxtok não controla essas plataformas e não garante disponibilidade ininterrupta de serviços de terceiros.</p>
      <h2>8. Licença de uso</h2><p>Durante a vigência do teste ou assinatura, o cliente recebe direito limitado, não exclusivo e não transferível de utilizar o Fluxtok para sua própria operação. O software, marca, identidade visual, código e materiais permanecem protegidos pelos direitos aplicáveis.</p>
      <h2>9. Uso proibido</h2><p>É proibido tentar acessar dados de outra empresa, explorar vulnerabilidades, contornar limites de plano, compartilhar credenciais de forma insegura, utilizar automações abusivas ou empregar o serviço para qualquer atividade ilícita.</p>
      <h2>10. Disponibilidade e responsabilidade</h2><p>O Fluxtok emprega medidas razoáveis de segurança e continuidade, mas serviços online podem sofrer interrupções. Indicadores, FluxScore e FluxRadar são recursos de apoio operacional e não constituem garantia de vendas, desempenho de creators ou resultado comercial.</p>
      <h2>11. Suporte</h2><p>O suporte pode ser prestado pelo módulo interno do Fluxtok e, quando configurado, por e-mail. Prazos de resposta podem variar de acordo com o plano e volume de solicitações.</p>
      <h2>12. Alterações</h2><p>Os Termos podem ser atualizados para refletir mudanças de produto, segurança, legislação ou integrações. Quando a alteração for material, recomenda-se comunicar os usuários e solicitar nova confirmação quando aplicável.</p>
      <h2>13. Legislação aplicável</h2><p>Aplica-se a legislação brasileira, inclusive normas de proteção de dados e defesa do consumidor quando forem juridicamente aplicáveis à relação.</p>
      <h2>14. Identificação do responsável</h2><p><strong>Preencher antes de divulgar comercialmente:</strong> nome/razão social do responsável pelo Fluxtok, CPF/CNPJ quando aplicável, cidade/UF, e-mail de suporte e canal de privacidade.</p>
    </article>
  </main>;
}
