import { prisma } from "@/lib/prisma";
import { requireSuperadmin } from "@/lib/auth";
import { Notice } from "@/components/notice";

export default async function Superadmin({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  await requireSuperadmin(); const q=await searchParams;
  const companies=await prisma.company.findMany({include:{users:{take:1,orderBy:{createdAt:"asc"}},_count:{select:{users:true,creators:true,samples:true,contents:true}},trial:true,subscription:true,tiktokConnection:true},orderBy:{createdAt:"desc"}});
  const active=companies.filter(c=>c.active).length; const paying=companies.filter(c=>c.subscription?.status==="ACTIVE").length; const trials=companies.filter(c=>c.subscription?.status==="TRIALING"&&c.subscription.trialEndsAt>new Date()).length;
  return <>
    <div className="page-head"><div><div className="eyebrow">FLUXTOK ADMIN</div><h1 className="page-title">Empresas</h1><p className="page-subtitle">Acompanhe cadastros, testes, assinaturas e uso do sistema.</p></div><a className="btn btn-primary" href="#nova-empresa">+ Criar manualmente</a></div>
    <div className="metric-grid metric-grid-3"><Metric label="Empresas" value={companies.length}/><Metric label="Em teste" value={trials}/><Metric label="Assinantes" value={paying} tone="success"/></div>
    {q.created&&<Notice>Empresa criada.</Notice>}{q.saved&&<Notice>Alteração salva.</Notice>}{q.error&&<Notice type="error">Não foi possível concluir a operação.</Notice>}
    <section className="form-card" id="nova-empresa"><div className="form-card-head"><div><h2>Criar acesso manual</h2><p>Normalmente o cliente cria a própria conta em /register. Use isto só quando necessário.</p></div></div><form className="stack" action="/api/superadmin/companies" method="post"><div className="form-grid compact-grid"><Field name="name" label="Empresa *"/><Field name="adminName" label="Responsável *"/><Field name="adminEmail" label="E-mail *" type="email"/><Field name="adminPassword" label="Senha inicial *" type="password" minLength={12}/></div><div className="form-actions"><button className="btn btn-primary">Criar com 7 dias grátis</button></div></form></section>
    <section className="section"><div className="section-bar"><div><h2>Empresas cadastradas</h2><p>{companies.length} empresa(s) · {active} ativa(s)</p></div></div><div className="table-wrap"><table className="table"><thead><tr><th>Empresa</th><th>Plano</th><th>Teste / status</th><th>TikTok</th><th>Uso</th><th></th></tr></thead><tbody>{companies.map(c=><tr key={c.id}><td><strong>{c.name}</strong><div className="cell-sub">{c.users[0]?.email || c.slug}</div></td><td>{c.subscription?.plan||"—"}</td><td><span className={`badge ${c.subscription?.status==="ACTIVE"?"tone-success":c.subscription?.status==="EXPIRED"?"tone-danger":"tone-warning"}`}>{c.subscription?.status||"LEGADO"}</span><div className="cell-sub">{c.subscription?.trialEndsAt?`Teste até ${c.subscription.trialEndsAt.toLocaleDateString("pt-BR")}`:""}</div></td><td>{c.tiktokConnection?.status==="CONNECTED"?<span className="badge tone-success">Conectado</span>:"—"}</td><td><div className="usage-line"><span>{c._count.users} user</span><span>{c._count.creators} creators</span><span>{c._count.samples} amostras</span><span>{c._count.contents} conteúdos</span></div></td><td><form action={`/api/superadmin/companies/${c.id}/toggle`} method="post"><button className="btn btn-mini">{c.active?"Desativar":"Ativar"}</button></form></td></tr>)}</tbody></table></div></section>
  </>;
}
function Field({name,label,type="text",minLength}:{name:string;label:string;type?:string;minLength?:number}){return <div className="field"><label>{label}</label><input name={name} type={type} required minLength={minLength}/></div>}
function Metric({label,value,tone}:{label:string;value:number;tone?:"success"}){return <div className={`metric-card ${tone?`metric-${tone}`:""}`}><div className="metric-label">{label}</div><div className="metric-value">{value}</div></div>}
