import { redirect } from "next/navigation";
import { getCurrentUser } from "@/lib/auth";
import { Brand } from "@/components/brand";
import { BillingPlan } from "@prisma/client";
import { ANNUAL_DISCOUNT_PERCENT, PLAN_INFO, annualMonthlyEquivalent, annualPrice } from "@/lib/billing";

export default async function Home() {
  const user = await getCurrentUser();
  if (user) redirect(user.role === "SUPERADMIN" ? "/superadmin" : "/dashboard");
  return <main className="landing fluxtok-landing">
    <header className="landing-nav container"><Brand /><nav className="public-nav"><a href="#como-funciona">Como funciona</a><a href="#recursos">Recursos</a><a href="#precos">Planos</a></nav><div className="header-actions"><a className="btn btn-ghost" href="/login">Entrar</a><a className="btn btn-primary" href="/register">Testar grátis</a></div></header>
    <section className="hero container hero-v3">
      <div className="hero-copy"><div className="eyebrow">CREATORS • AMOSTRAS • CONTEÚDO • COMMERCE</div><h1>Organize a operação com creators sem transformar tudo em planilha.</h1><p>O Fluxtok centraliza creators, campanhas, amostras e publicações. Conecte sua TikTok Shop, acompanhe pendências e saiba o que precisa acontecer a seguir.</p><div className="hero-actions"><a className="btn btn-primary btn-lg" href="/register">Começar 7 dias grátis</a><a className="btn btn-ghost btn-lg" href="#como-funciona">Ver como funciona</a></div><div className="hero-trust">Sem cartão para testar · Dados separados por empresa · HTTPS e sessões seguras</div></div>
      <div className="hero-panel hero-panel-v3"><div className="mini-header"><span></span><span></span><span></span><b>Fluxtok</b></div><div className="hero-metrics"><div><small>Creators ativos</small><strong>24</strong></div><div><small>Pendentes</small><strong>6</strong></div><div><small>Publicados</small><strong>38</strong></div></div><div className="mini-row danger-dot"><b>@joao</b><span>Kit Skincare</span><em>4 dias atrasado</em></div><div className="mini-row warning-dot"><b>@maria</b><span>Campanha Glow</span><em>vence amanhã</em></div><div className="mini-row success-dot"><b>@ana</b><span>Vídeo publicado</span><em>concluído</em></div><div className="sync-strip">♪ TikTok Shop <span>Produtos sincronizados</span></div></div>
    </section>
    <section id="como-funciona" className="container landing-section"><div className="section-heading"><span>FLUXO SIMPLES</span><h2>Do creator encontrado à publicação registrada.</h2></div><div className="feature-grid"><Feature n="01" title="Cadastre ou conecte" text="Comece manualmente ou conecte o TikTok Shop para trazer produtos."/><Feature n="02" title="Monte a operação" text="Organize creators, produtos e campanhas sem telas desnecessárias."/><Feature n="03" title="Acompanhe amostras" text="Veja envio, recebimento, prazo e conteúdo pendente em um só lugar."/><Feature n="04" title="Feche o ciclo" text="Registre publicação, visualizações, vendas e faturamento."/></div></section>
    <section id="recursos" className="container landing-section"><div className="section-heading"><span>DIFERENCIAL</span><h2>Menos painel para olhar. Mais clareza sobre o que fazer.</h2></div><div className="resource-grid"><Resource title="FluxRadar" text="Transforma os dados da operação em uma lista priorizada de próximas ações."/><Resource title="FluxScore" text="Indicador transparente de consistência do creator com publicação, prazo e vendas registradas."/><Resource title="TikTok Shop" text="OAuth oficial, identificação da loja e sincronização de produtos."/><Resource title="Suporte dentro do app" text="Abra chamados, acompanhe respostas e mantenha o histórico por empresa."/><Resource title="7 dias grátis" text="Cadastro automático da empresa, sem cartão, com controle de prazo pelo Superadmin."/><Resource title="Assinatura" text={`Planos mensais e anuais com ${ANNUAL_DISCOUNT_PERCENT}% de desconto no ciclo anual e checkout recorrente via Mercado Pago.`}/></div></section>
    <section id="precos" className="container landing-section pricing-section"><div className="section-heading"><span>PLANOS</span><h2>Teste primeiro. Assine quando fizer sentido.</h2><p>Os valores podem ser ajustados pelo administrador sem alterar o código.</p></div><div className="pricing-grid"><Price plan={BillingPlan.STARTER} items={["Creators, produtos e amostras","Campanhas e pendências","TikTok Shop","Até 3 usuários"]}/><Price plan={BillingPlan.PRO} featured items={["Tudo do Essencial","Mais usuários","Indicadores e auditoria","Prioridade em novos recursos"]}/></div><div className="center-actions"><a className="btn btn-primary btn-lg" href="/register">Criar conta grátis</a></div></section>
    <footer className="landing-footer container"><Brand /><span>Fluxtok não é afiliado nem endossado pelo TikTok. TikTok é marca de seus respectivos titulares. · <a href="/termos">Termos</a> · <a href="/privacidade">Privacidade</a></span></footer>
  </main>;
}

function Feature({n,title,text}:{n:string;title:string;text:string}){return <article className="feature-card"><div className="feature-number">{n}</div><h3>{title}</h3><p>{text}</p></article>}
function Resource({title,text}:{title:string;text:string}){return <article className="resource-card"><span>↗</span><h3>{title}</h3><p>{text}</p></article>}
function Price({plan,items,featured=false}:{plan:BillingPlan;items:string[];featured?:boolean}){const info=PLAN_INFO[plan];const annual=annualPrice(plan);const eq=annualMonthlyEquivalent(plan);const money=(v:number)=>v.toFixed(2).replace(".",",");return <article className={`price-card ${featured?"price-featured":""}`}>{featured&&<div className="price-badge">Mais completo</div>}<h3>{info.name}</h3><div className="price"><strong>R$ {money(info.price)}</strong><span>/mês</span></div><div className="annual-price-line"><strong>Anual: R$ {money(annual)}</strong><span>{ANNUAL_DISCOUNT_PERCENT}% de desconto · equivale a R$ {money(eq)}/mês</span></div><ul>{items.map(i=><li key={i}>✓ {i}</li>)}</ul><a className={`btn btn-lg ${featured?"btn-primary":"btn-soft"}`} href="/register">Testar 7 dias</a></article>}
