import { requireSuperadmin } from "@/lib/auth";
import { getPlatformSettings } from "@/lib/platform-settings";
import { Notice } from "@/components/notice";

export default async function AdminSettings({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  await requireSuperadmin(); const q = await searchParams; const settings = await getPlatformSettings();
  const smtpReady = Boolean(process.env.SMTP_HOST && process.env.SMTP_USER && process.env.SMTP_PASS);
  const mpReady = Boolean(process.env.MERCADOPAGO_ACCESS_TOKEN && process.env.MERCADOPAGO_WEBHOOK_SECRET);
  return <>
    <div className="page-head"><div><div className="eyebrow">PLATAFORMA</div><h1 className="page-title">Configurações do Fluxtok</h1><p className="page-subtitle">Defina os canais que aparecem para clientes e acompanhe integrações essenciais.</p></div></div>
    {q.saved && <Notice>Configurações salvas.</Notice>}{q.error === "no-email" && <Notice type="error">Cadastre primeiro o e-mail que recebe notificações.</Notice>}{q.error && q.error !== "no-email" && <Notice type="error">Confira os e-mails informados.</Notice>}{q["email-test"] === "ok" && <Notice>E-mail de teste enviado. Confira a caixa de entrada e o spam.</Notice>}{q["email-test"] === "missing-smtp" && <Notice type="error">O e-mail está cadastrado, mas o SMTP ainda não está configurado nas Variables.</Notice>}{q["email-test"] === "error" && <Notice type="error">O SMTP respondeu com erro. Confira host, porta, usuário e senha.</Notice>}
    <div className="settings-grid"><section className="form-card"><div className="form-card-head"><div><h2>Suporte</h2><p>Esses e-mails podem ser alterados sem novo deploy.</p></div></div><form className="stack" action="/api/superadmin/settings" method="post"><div className="field"><label>Nome exibido no suporte</label><input name="supportName" defaultValue={settings.supportName} required minLength={2}/></div><div className="field"><label>E-mail público de suporte</label><input name="supportEmail" type="email" defaultValue={settings.supportEmail || ""} placeholder="suporte@fluxtok.com.br"/></div><div className="field"><label>E-mail que recebe notificações</label><input name="notificationEmail" type="email" defaultValue={settings.notificationEmail || ""} placeholder="seuemail@gmail.com"/></div><div className="form-actions"><button className="btn btn-primary">Salvar</button></div></form>{settings.notificationEmail && <form action="/api/superadmin/settings/test-email" method="post" className="inline-test-form"><button className="btn btn-soft">Enviar e-mail de teste</button></form>}</section><section className="form-card"><div className="form-card-head"><div><h2>Status das integrações</h2><p>Secrets continuam protegidos nas variáveis do Railway.</p></div></div><div className="integration-health"><Health label="SMTP / e-mail" ok={smtpReady}/><Health label="Mercado Pago" ok={mpReady}/><Health label="APP_URL" ok={Boolean(process.env.APP_URL)}/><Health label="SESSION_SECRET" ok={Boolean(process.env.SESSION_SECRET && process.env.SESSION_SECRET.length >= 32)}/></div><p className="mini-help">O e-mail salvo acima define o canal e destinatário. Para enviar mensagens de verdade, configure SMTP nas variáveis do Railway. Com Gmail, use smtp.gmail.com, porta 465, SMTP_SECURE=true e uma Senha de app — nunca a senha normal da conta.</p></section></div>
  </>;
}
function Health({label,ok}:{label:string;ok:boolean}){return <div className="health-row"><span>{label}</span><b className={ok?"health-ok":"health-warn"}>{ok?"Configurado":"Pendente"}</b></div>}
