import { prisma } from "@/lib/prisma";
import { requireSuperadmin } from "@/lib/auth";
import { Notice } from "@/components/notice";

export default async function CompaniesPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  await requireSuperadmin(); const q = await searchParams;
  const companies = await prisma.company.findMany({ include: { users: { take: 1, orderBy: { createdAt: "asc" } }, _count: { select: { users: true, creators: true, samples: true, contents: true } }, trial: true, subscription: true, tiktokConnection: true }, orderBy: { createdAt: "desc" } });
  return <>
    <div className="page-head"><div><div className="eyebrow">CLIENTES</div><h1 className="page-title">Empresas</h1><p className="page-subtitle">Gerencie acesso, teste gratuito e uso de cada conta.</p></div><a className="btn btn-primary" href="#nova-empresa">+ Criar manualmente</a></div>
    {q.created && <Notice>Empresa criada.</Notice>}{q.saved && <Notice>Alteração salva.</Notice>}{q.error && <Notice type="error">Não foi possível concluir a operação.</Notice>}
    <section className="form-card" id="nova-empresa"><div className="form-card-head"><div><h2>Criar acesso manual</h2><p>O cadastro público continua sendo o fluxo principal. Use isto para demonstrações, parceiros ou clientes assistidos.</p></div></div><form className="stack" action="/api/superadmin/companies" method="post"><div className="form-grid compact-grid"><Field name="name" label="Empresa *"/><Field name="adminName" label="Responsável *"/><Field name="adminEmail" label="E-mail *" type="email"/><Field name="adminPassword" label="Senha inicial *" type="password" minLength={12}/></div><div className="form-actions"><button className="btn btn-primary">Criar com 7 dias grátis</button></div></form></section>
    <section className="section"><div className="section-bar"><div><h2>Empresas cadastradas</h2><p>{companies.length} empresa(s)</p></div></div><div className="company-admin-grid">{companies.map((c) => <article className="company-admin-card" key={c.id}><div className="company-admin-head"><div><strong>{c.name}</strong><span>{c.users[0]?.email || c.slug}</span></div><span className={`badge ${c.active ? "tone-success" : "tone-danger"}`}>{c.active ? "Ativa" : "Desativada"}</span></div><div className="company-admin-meta"><span><b>Plano</b>{c.subscription?.plan || "—"}</span><span><b>Status</b>{c.subscription?.status || "LEGADO"}</span><span><b>Teste até</b>{c.subscription?.trialEndsAt?.toLocaleDateString("pt-BR") || c.trial?.trialEndsAt?.toLocaleDateString("pt-BR") || "—"}</span><span><b>TikTok</b>{c.tiktokConnection?.status === "CONNECTED" ? "Conectado" : "Manual"}</span></div><div className="usage-line"><span>{c._count.users} usuário(s)</span><span>{c._count.creators} creators</span><span>{c._count.samples} amostras</span><span>{c._count.contents} conteúdos</span></div><div className="trial-extension"><strong>Adicionar dias de teste</strong><form action={`/api/superadmin/companies/${c.id}/trial`} method="post"><input name="days" type="number" min="1" max="365" defaultValue="7" required/><button className="btn btn-mini">Adicionar dias</button></form><div className="trial-shortcuts">{[1,3,7,14,30].map((days)=><form key={days} action={`/api/superadmin/companies/${c.id}/trial`} method="post"><input type="hidden" name="days" value={days}/><button className="btn btn-ghost btn-mini">+{days}d</button></form>)}</div></div><div className="company-admin-actions"><form action={`/api/superadmin/companies/${c.id}/toggle`} method="post"><button className={`btn btn-mini ${c.active ? "btn-danger-soft" : "btn-soft"}`}>{c.active ? "Desativar conta" : "Reativar conta"}</button></form></div></article>)}</div></section>
  </>;
}
function Field({name,label,type="text",minLength}:{name:string;label:string;type?:string;minLength?:number}){return <div className="field"><label>{label}</label><input name={name} type={type} required minLength={minLength}/></div>}
